services:
  # Django web application
  web_app:
    build: .
    container_name: web_app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./locallibrary_tutorial:/locallibrary_tutorial
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - locallibrary_network


  # PostgreSQL database
  postgres_db:
    image: postgres:latest
    healthcheck:
      test: pg_isready -d locallibrary_db
      interval: 2s
      timeout: 5s
      retries: 15
    container_name: postgres_db 
    restart: always
    environment:
      - POSTGRES_DB=locallibrary_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - locallibrary_network
   
volumes:
  postgres_db:
    driver: local

networks:
  locallibrary_network:
